"""initial migration

Revision ID: 42ddcf7d3fe9
Revises: 
Create Date: 2026-08-09 21:24:19.336651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ddcf7d3fe9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('condicion_iva', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cuit'), 'clientes', ['cuit'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('revisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisiones_entidad_id'), 'revisiones', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_revisiones_entidad_tipo'), 'revisiones', ['entidad_tipo'], unique=False)
    op.create_index(op.f('ix_revisiones_id'), 'revisiones', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('comprobantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('confirmado_por', sa.String(length=50), nullable=False),
    sa.Column('confirmado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comprobantes_cliente_id'), 'comprobantes', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_comprobantes_id'), 'comprobantes', ['id'], unique=False)
    op.create_table('lineas_alicuota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('alicuota', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('neto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineas_alicuota')
    op.drop_index(op.f('ix_comprobantes_id'), table_name='comprobantes')
    op.drop_index(op.f('ix_comprobantes_cliente_id'), table_name='comprobantes')
    op.drop_table('comprobantes')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_revisiones_id'), table_name='revisiones')
    op.drop_index(op.f('ix_revisiones_entidad_tipo'), table_name='revisiones')
    op.drop_index(op.f('ix_revisiones_entidad_id'), table_name='revisiones')
    op.drop_table('revisiones')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cuit'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
